# Generated by Django 4.1 on 2022-08-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authoer',
            new_name='author',
        ),
    ]
